#docker-compose.yml
version: "2"

services:
  app:
    build: .
    container_name: bot_service_appointment
    restart: unless-stopped
    env_file: .env
    environment:
      # Путь до ключа внутри контейнера
      - GOOGLE_CREDENTIALS_FILE=/app/creds/nixos-ai-001-051cfeb5722e.json
    volumes:
      - ./database:/app/database/
      - ./logs/:/app/logs/
      - ./nixos-ai-001-051cfeb5722e.json:/app/creds/nixos-ai-001-051cfeb5722e.json:ro
    command: ["python", "main.py"]
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f main.py >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
