services:
  miniapp-api:
    build: .
    container_name: lesson_record_bot_miniapi
    restart: unless-stopped
    env_file: .env.testbot.docker
    environment:
      - DB_PATH=/app/data/test_bot.db
      - WEBAPI_PORT=8000
    volumes:
      - ./database:/app/data
      - ./logs:/app/logs
    entrypoint: ["python", "main_webapi.py"]
    ports:
      - "127.0.0.1:18000:8000"

  miniapp-frontend:
    image: node:20-alpine
    container_name: lesson_record_bot_miniapp_front
    working_dir: /frontend
    volumes:
      - ./miniapp:/frontend
    command: sh -c "npm ci && npm run build && npx serve -s dist -l 15173"
    environment:
      - VITE_API_BASE=https://axtar-b2b.ru/miniapi
    ports:
      - "127.0.0.1:15173:15173"
